import os
import zipfile

def zipdir(path, ziph):
    for root, dirs, files in os.walk(path):
        # Exclude pycache, hidden git folders, and staticfiles (which is generated by Render)
        dirs[:] = [d for d in dirs if d not in ('__pycache__', '.pytest_cache', '.git', 'staticfiles', '.venv', 'venv', 'env')]
        for file in files:
            if file.endswith('.zip') or file.endswith('.pyc') or file == "zip_project.py":
                continue
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, path)
            ziph.write(file_path, arcname)

if os.path.exists('listextinctanimals_production.zip'):
    os.remove('listextinctanimals_production.zip')

zipf = zipfile.ZipFile('listextinctanimals_production.zip', 'w', zipfile.ZIP_DEFLATED)
zipdir('.', zipf)
zipf.close()
print(f"Novo Zip criado com sucesso. Tamanho: {os.path.getsize('listextinctanimals_production.zip') / (1024*1024):.2f} MB")
