"""
Script de Sincronizacao v18 - 114 especies validadas
Executa: python manage.py shell < sync_mammals_v18.py
"""

import os
import sys

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "extinct_mammals_django.settings")
django.setup()

from collections import Counter

from mammals.models import Mammal

SPECIES_DATA = [
    (
        "Noronhomys vespuccii",
        "Rato de Vespucci / Noronhomys",
        "Rodentia",
        "Fernando de Noronha, Brasil",
        1503,
        "IUCN 2008",
        2008,
        "Americas",
        "Colonizacao europeia, predacao por ratos introduzidos",
    ),
    (
        "Hippopotamus madagascariensis",
        "Hipopotamo-anao-de-madagascar",
        "Artiodactyla",
        "Madagascar",
        1500,
        "IUCN 2008",
        2008,
        "Madagascar",
        "Caca humana, alteracao de habitat florestal",
    ),
    (
        "Boromys offella",
        "Rato-de-caverna oriente",
        "Rodentia",
        "Cuba",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, caca, especies invasoras",
    ),
    (
        "Boromys torrei",
        "Rato-de-caverna de Torre",
        "Rodentia",
        "Cuba",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, caca, especies invasoras",
    ),
    (
        "Hexolobodon phenax",
        "Hutia impostora",
        "Rodentia",
        "Hispaniola (Haiti/Rep. Dom.)",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca, especies invasoras, desmatamento",
    ),
    (
        "Isolobodon montanus",
        "Hutia montanhesa",
        "Rodentia",
        "Hispaniola",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca, especies invasoras",
    ),
    (
        "Geocapromys columbianus",
        "Coelho-de-Cuba / Cuban coney",
        "Rodentia",
        "Cuba",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca, desmatamento, especies invasoras",
    ),
    (
        "Conilurus capricornensis",
        "Rato-coelho de Capricornio",
        "Rodentia",
        "Queensland, Australia",
        1500,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por especies invasoras",
    ),
    (
        "Plagiodontia ipnaeum",
        "Hutia de Samana",
        "Rodentia",
        "Hispaniola",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao, caca, especies invasoras",
    ),
    (
        "Antillothrix bernensis",
        "Macaco-de-Hispaniola",
        "Primates",
        "Hispaniola (Rep. Dominicana)",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, caca, desmatamento",
    ),
    (
        "Heteropsomys insulans",
        "Rato-de-caverna insular",
        "Rodentia",
        "Ilha de Vieques, Porto Rico",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Coryphomys buehleri",
        "Coryphomys de Buhler",
        "Rodentia",
        "Timor Ocidental, Indonesia",
        1500,
        "IUCN 2016",
        2016,
        "Asia",
        "Especies invasoras, caca",
    ),
    (
        "Nesophontes edithae",
        "Nesofonte porto-riquenho",
        "Eulipotyphla",
        "Porto Rico",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras (ratos)",
    ),
    (
        "Nesophontes hypomicrus",
        "Nesofonte de Atalaye",
        "Eulipotyphla",
        "Hispaniola",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Nesophontes major",
        "Grande nesofonte cubano",
        "Eulipotyphla",
        "Cuba",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Nesophontes micrus",
        "Nesofonte cubano ocidental",
        "Eulipotyphla",
        "Cuba (inc. Isla de la Juventud)",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Nesophontes paramicrus",
        "Nesofonte de Sao Miguel",
        "Eulipotyphla",
        "Hispaniola",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Nesophontes zamicrus",
        "Nesofonte haitiano",
        "Eulipotyphla",
        "Haiti",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Solenodon marcanoi",
        "Solenodonte de Marcano",
        "Eulipotyphla",
        "Republica Dominicana",
        1500,
        "IUCN 2014",
        2014,
        "Caribe",
        "Colonizacao, predadores introduzidos",
    ),
    (
        "Hippopotamus lemerlei",
        "Hipopotamo-anao de Lemerle",
        "Artiodactyla",
        "Madagascar",
        1500,
        "IUCN 2008",
        2008,
        "Madagascar",
        "Caca humana, colonizacao",
    ),
    (
        "Dusicyon avus",
        "Dusicyon avus",
        "Carnivora",
        "Argentina, Chile, Brasil, Uruguai",
        1500,
        "IUCN 2015",
        2015,
        "Americas",
        "Caca, pressao humana",
    ),
    (
        "Pennatomys nivalis",
        "Rato-de-arroz de Nevis",
        "Rodentia",
        "Sint Eustatius / St. Kitts-Nevis",
        1500,
        "IUCN 2012",
        2012,
        "Caribe",
        "Colonizacao, especies invasoras",
    ),
    (
        "Bettongia pusilla",
        "Bettong-de-Nullarbor",
        "Diprotodontia",
        "Planicie de Nullarbor, Australia",
        1500,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por especies invasoras",
    ),
    (
        "Megaoryzomys curioi",
        "Rato-gigante-das-Galapagos",
        "Rodentia",
        "Ilha Santa Cruz, Galapagos",
        1500,
        "IUCN 2008",
        2008,
        "Oceano",
        "Especies invasoras (ratos, gatos)",
    ),
    (
        "Brotomys voratus",
        "Rato-comestivel de Hispaniola",
        "Rodentia",
        "Hispaniola",
        1546,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, caca",
    ),
    (
        "Palaeopropithecus ingens",
        "Lemure-preguica gigante",
        "Primates",
        "Madagascar",
        1620,
        "IUCN 2021",
        2021,
        "Madagascar",
        "Caca, desmatamento, colonizacao",
    ),
    (
        "Bos primigenius",
        "Uro / Auroque",
        "Artiodactyla",
        "Europa (ultimo: Polonia)",
        1627,
        "IUCN 2008",
        2008,
        "Europa",
        "Caca excessiva, hibridizacao, perda de habitat",
    ),
    (
        "Cryptoprocta spelea",
        "Fossa gigante",
        "Carnivora",
        "Madagascar",
        1658,
        "IUCN 2008",
        2008,
        "Madagascar",
        "Caca, colonizacao, competicao com especies invasoras",
    ),
    (
        "Nesophontes hemicingulus",
        "Nesofonte-das-ilhas-cayman",
        "Eulipotyphla",
        "Ilhas Cayman (Grand Cayman, Cayman Brac)",
        1700,
        "IUCN 2017",
        2017,
        "Caribe",
        "Predadores exoticos (ratos negros)",
    ),
    (
        "Xenothrix mcgregori",
        "Macaco-da-Jamaica",
        "Primates",
        "Jamaica",
        1700,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca, desmatamento, especies invasoras",
    ),
    (
        "Hydrodamalis gigas",
        "Vaca-marinha-de-Steller",
        "Sirenia",
        "Ilhas Commander, Russia / EUA",
        1768,
        "lit. 1768",
        1768,
        "Oceano",
        "Caca (carne, couro, gordura) por cacadores de peles",
    ),
    (
        "Prolagus sardus",
        "Pica-de-Sardenha",
        "Lagomorpha",
        "Corsega e Sardenha",
        1774,
        "IUCN 2008",
        2008,
        "Europa",
        "Predacao por especies invasoras, caca",
    ),
    (
        "Hippotragus leucophaeus",
        "Hipotrago-azul / Bluebuck",
        "Artiodactyla",
        "Cabo da Boa Esperanca, Africa do Sul",
        1800,
        "IUCN 2008",
        2008,
        "Africa",
        "Caca por colonos europeus, perda de habitat",
    ),
    (
        "Conilurus albipes",
        "Rato-de-pes-brancos",
        "Rodentia",
        "Costa leste da Australia",
        1862,
        "IUCN 2008",
        2008,
        "Australia",
        "Predacao por gatos e raposas, destruicao de habitat",
    ),
    (
        "Pteropus coxi",
        "Raposa-voadora-grande-de-Samoa",
        "Chiroptera",
        "Samoa",
        1840,
        "IUCN 2020",
        2020,
        "Oceano",
        "Caca, desmatamento",
    ),
    (
        "Notomys macrotis",
        "Rato-saltador-de-orelhas-grandes",
        "Rodentia",
        "Australia Ocidental central",
        1843,
        "IUCN 2008",
        2008,
        "Australia",
        "Destruicao de habitat, predacao por especies invasoras",
    ),
    (
        "Notomys mordax",
        "Rato-saltador-de-Darling-Downs",
        "Rodentia",
        "Queensland, Australia",
        1846,
        "IUCN 2008",
        2008,
        "Australia",
        "Destruicao de habitat, especies invasoras",
    ),
    (
        "Pseudomys auritus",
        "Rato-de-orelhas-longas",
        "Rodentia",
        "Australia do Sul (localizacao incerta)",
        1850,
        "IUCN 2008",
        2008,
        "Australia",
        "Predacao por especies invasoras, alteracao de habitat",
    ),
    (
        "Pteropus allenorum",
        "Raposa-voadora-pequena-de-Samoa",
        "Chiroptera",
        "Samoa (Upolu, Polinesia Ocidental)",
        1856,
        "IUCN 2020",
        2020,
        "Oceano",
        "Caca, desmatamento",
    ),
    (
        "Pseudomys gouldii",
        "Rato-de-Gould",
        "Rodentia",
        "Metade sul da Australia",
        1930,
        "IUCN 2008",
        2008,
        "Australia",
        "Predacao por gatos e raposas, alteracao de habitat",
    ),
    (
        "Pteropus subniger",
        "Raposa-voadora-menor-das-Mascarenhas",
        "Chiroptera",
        "Reuniao, Mauricio",
        1864,
        "IUCN 2017",
        2017,
        "Oceano",
        "Caca, desmatamento",
    ),
    (
        "Pteropus brunneus",
        "Raposa-voadora-de-Percy",
        "Chiroptera",
        "Ilhas Percy, Australia",
        1870,
        "IUCN 2017",
        2017,
        "Australia",
        "Caca, desmatamento",
    ),
    (
        "Pteropus pilosus",
        "Raposa-voadora-de-Palau",
        "Chiroptera",
        "Palau",
        1874,
        "IUCN 2017",
        2017,
        "Oceano",
        "Caca, perda de habitat",
    ),
    (
        "Potorous platyops",
        "Potoroo-de-face-larga",
        "Diprotodontia",
        "Australia do Sul / Ocidental",
        1875,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por gatos e raposas, caca",
    ),
    (
        "Dusicyon australis",
        "Lobo-das-Malvinas / Warrah",
        "Carnivora",
        "Ilhas Malvinas (Falkland)",
        1876,
        "IUCN 2008",
        2008,
        "Americas",
        "Caca deliberada por colonos (envenenamento)",
    ),
    (
        "Oryzomys antillarum",
        "Rato-de-arroz-da-Jamaica",
        "Rodentia",
        "Jamaica",
        1877,
        "IUCN 2008",
        2008,
        "Caribe",
        "Especies invasoras (mangustas), perda de habitat",
    ),
    (
        "Megalomys luciae",
        "Rato-gigante-de-Santa-Lucia",
        "Rodentia",
        "Santa Lucia",
        1881,
        "IUCN 2008",
        2008,
        "Caribe",
        "Introducao de mangustas",
    ),
    (
        "Pipistrellus sturdeei",
        "Rato-pipistrelo-das-Bonin",
        "Chiroptera",
        "Ilhas Bonin (Ogasawara), Japao",
        1889,
        "IUCN 2008",
        2008,
        "Asia",
        "Perda de habitat, especies invasoras",
    ),
    (
        "Lagorchestes leporides",
        "Ualabi-lebre oriental",
        "Diprotodontia",
        "Australia",
        1889,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por raposas, caca, alteracao de habitat",
    ),
    (
        "Oligoryzomys victus",
        "Rato-de-arroz-de-Sao-Vicente",
        "Rodentia",
        "Sao Vicente",
        1892,
        "IUCN 2008",
        2008,
        "Caribe",
        "Introducao de mangustas, especies invasoras",
    ),
    (
        "Sus bucculentus",
        "Javali-verrugoso-da-Indochina",
        "Artiodactyla",
        "Vietna",
        1892,
        "IUCN 2016",
        2016,
        "Asia",
        "Caca, perda de habitat",
    ),
    (
        "Acerodon lucifer",
        "Raposa-voadora-de-Panay",
        "Chiroptera",
        "Ilha de Panay, Filipinas",
        1892,
        "IUCN 2008",
        2008,
        "Asia",
        "Caca, destruicao de habitat",
    ),
    (
        "Neogale macrodon",
        "Rato-almiscarado / Sea mink",
        "Carnivora",
        "EUA (Maine, Mass.) e Canada (NB, NF)",
        1894,
        "lit. 1903",
        1903,
        "Americas",
        "Caca pelo comercio de peles",
    ),
    (
        "Eudorcas rufina",
        "Gazela-vermelha",
        "Artiodactyla",
        "Argelia",
        1894,
        "IUCN 2008",
        2008,
        "Africa",
        "Caca excessiva",
    ),
    (
        "Notomys amplus",
        "Rato-saltador-de-cauda-curta",
        "Rodentia",
        "Grande Deserto de Areia, Australia",
        1896,
        "IUCN 2008",
        2008,
        "Australia",
        "Destruicao de habitat, predacao por especies invasoras",
    ),
    (
        "Oryzomys nelsoni",
        "Rato-de-arroz-de-Nelson",
        "Rodentia",
        "Ilhas Marias, Mexico",
        1897,
        "IUCN 2008",
        2008,
        "Americas",
        "Caca, especies invasoras (gatos, ratos)",
    ),
    (
        "Notomys longicaudatus",
        "Rato-saltador-de-cauda-longa",
        "Rodentia",
        "Australia",
        1901,
        "IUCN 2008",
        2008,
        "Australia",
        "Predacao por especies invasoras, perda de habitat",
    ),
    (
        "Megalomys desmarestii",
        "Rato-gigante-da-Martinica",
        "Rodentia",
        "Martinica",
        1902,
        "IUCN 2008",
        2008,
        "Caribe",
        "Erupcao do Monte Pelee (1902), mangustas introduzidas",
    ),
    (
        "Rattus macleari",
        "Rato-de-Maclear",
        "Rodentia",
        "Ilha Christmas",
        1903,
        "IUCN 2008",
        2008,
        "Oceano",
        "Tripanosomiase introduzida por ratos negros",
    ),
    (
        "Rattus nativitatis",
        "Rato-buldogue",
        "Rodentia",
        "Ilha Christmas",
        1903,
        "IUCN 2008",
        2008,
        "Oceano",
        "Tripanosomiase introduzida por ratos negros",
    ),
    (
        "Lagostomus crassus",
        "Viscacha-ana",
        "Rodentia",
        "Peru",
        1910,
        "IUCN 2008",
        2008,
        "Americas",
        "Caca, perda de habitat",
    ),
    (
        "Neotoma anthonyi",
        "Rato-aninhador de Anthony",
        "Rodentia",
        "Isla Todos Santos, Mexico",
        1926,
        "IUCN 2008",
        2008,
        "Americas",
        "Especies invasoras (gatos, ratos negros)",
    ),
    (
        "Perameles papillon",
        "Bandicoot-barrado-de-Nullarbor",
        "Peramelemorphia",
        "Planicie de Nullarbor, Australia",
        1928,
        "IUCN 2019",
        2019,
        "Australia",
        "Destruicao de habitat, predacao por especies invasoras",
    ),
    (
        "Nesoryzomys darwini",
        "Rato-de-Darwin das Galapagos",
        "Rodentia",
        "Galapagos (Santa Cruz)",
        1930,
        "IUCN 2008",
        2008,
        "Oceano",
        "Especies invasoras (ratos, gatos)",
    ),
    (
        "Peromyscus pembertoni",
        "Rato-veado-de-Pemberton",
        "Rodentia",
        "Ilha San Pedro Nolasco, Mexico",
        1931,
        "IUCN 2008",
        2008,
        "Americas",
        "Especies invasoras (gatos ferais)",
    ),
    (
        "Neotoma bunkeri",
        "Rato-aninhador de Bunker",
        "Rodentia",
        "Ilhas Coronado, Mexico",
        1931,
        "IUCN 2008",
        2008,
        "Americas",
        "Especies invasoras (gatos, ratos)",
    ),
    (
        "Perameles eremiana",
        "Bandicoot-do-deserto",
        "Peramelemorphia",
        "Australia central",
        1931,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por gatos e raposas, alteracao de habitat",
    ),
    (
        "Lagorchestes asomatus",
        "Ualabi-lebre do lago Mackay",
        "Diprotodontia",
        "Australia",
        1932,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por raposas, destruicao de habitat",
    ),
    (
        "Leporillus apicalis",
        "Rato-palito-menor",
        "Rodentia",
        "Australia centro-ocidental",
        1933,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por gatos ferais, raposas, destruicao habitat",
    ),
    (
        "Bettongia anhydra",
        "Bettong-do-deserto",
        "Diprotodontia",
        "Australia",
        1950,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por raposas, alteracao de habitat",
    ),
    (
        "Nesoryzomys indefessus",
        "Rato-indefatigavel das Galapagos",
        "Rodentia",
        "Galapagos (Santa Cruz)",
        1934,
        "IUCN 2008",
        2008,
        "Oceano",
        "Especies invasoras (ratos, gatos)",
    ),
    (
        "Caloprymnus campestris",
        "Canguru-rato-do-deserto",
        "Diprotodontia",
        "Australia",
        1935,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por raposas e gatos, seca, alteracao de habitat",
    ),
    (
        "Thylacinus cynocephalus",
        "Tilacino / Lobo-da-Tasmania",
        "Dasyuromorphia",
        "Australia, Tasmania, Nova Guine",
        1936,
        "IUCN 1982",
        1982,
        "Australia",
        "Caca sistematica (bounty), destruicao de habitat",
    ),
    (
        "Rucervus schomburgki",
        "Veado-de-Schomburgk",
        "Artiodactyla",
        "Tailandia",
        1932,
        "IUCN 1994",
        1994,
        "Asia",
        "Caca excessiva, perda de habitat",
    ),
    (
        "Macropus greyi",
        "Ualabi-toolache",
        "Diprotodontia",
        "Sul da Australia",
        1939,
        "IUCN 1996",
        1996,
        "Australia",
        "Caca esportiva, predacao por raposas",
    ),
    (
        "Perameles fasciata",
        "Bandicoot-barrado de NSW",
        "Peramelemorphia",
        "New South Wales, Australia",
        1846,
        "IUCN 2025",
        2025,
        "Australia",
        "Destruicao de habitat, predacao por gatos e raposas",
    ),
    (
        "Perameles myosuros",
        "Marl / Bandicoot-focinho-longo sudoeste",
        "Peramelemorphia",
        "Australia Ocidental",
        1907,
        "IUCN 2025",
        2025,
        "Australia",
        "Destruicao de habitat, predacao por especies invasoras",
    ),
    (
        "Chaeropus ecaudatus",
        "Bandicoot-de-pes-de-porco do sul",
        "Peramelemorphia",
        "Australia",
        1945,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por gatos e raposas, alteracao de habitat",
    ),
    (
        "Gazella bilkis",
        "Gazela-da-Rainha-de-Saba",
        "Artiodactyla",
        "Iemen",
        1951,
        "IUCN 1996",
        1996,
        "Asia",
        "Caca excessiva",
    ),
    (
        "Neomonachus tropicalis",
        "Foca-monge-do-Caribe",
        "Carnivora",
        "Mar do Caribe",
        1952,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca comercial, perseguicao",
    ),
    (
        "Geocapromys thoracatus",
        "Hutia-de-Swan-Island-menor",
        "Rodentia",
        "Ilhas Swan, Honduras",
        1955,
        "IUCN 2008",
        2008,
        "Americas",
        "Introducao de gatos ferais, caca",
    ),
    (
        "Onychogalea lunata",
        "Ualabi-de-cauda-crescente",
        "Diprotodontia",
        "Australia ocidental e central",
        1956,
        "IUCN 1996",
        1996,
        "Australia",
        "Predacao por raposas, caca, destruicao de habitat",
    ),
    (
        "Pseudomys glaucus",
        "Rato-azul-acinzentado",
        "Rodentia",
        "Queensland e NSW, Australia",
        1956,
        "IUCN 2008",
        2008,
        "Australia",
        "Predacao por especies invasoras, perda de habitat",
    ),
    (
        "Perameles notina",
        "Bandicoot-barrado do sul",
        "Peramelemorphia",
        "Sul da Australia",
        1900,
        "IUCN 2025",
        2025,
        "Australia",
        "Destruicao de habitat, predacao por especies invasoras",
    ),
    (
        "Chaeropus yirratji",
        "Bandicoot-de-pes-de-porco do norte",
        "Peramelemorphia",
        "Australia",
        1950,
        "IUCN 2019",
        2019,
        "Australia",
        "Predacao por especies invasoras",
    ),
    (
        "Neotoma martinensis",
        "Rato-da-madeira-de-San-Martin",
        "Rodentia",
        "Ilha San Martin, Mexico",
        1950,
        "IUCN 2008",
        2008,
        "Americas",
        "Predacao por especies invasoras (gatos ferais)",
    ),
    (
        "Juscelinomys candango",
        "Rato-de-Brasilia",
        "Rodentia",
        "Brasil central (Brasilia)",
        1960,
        "IUCN 2008",
        2008,
        "Americas",
        "Destruicao do habitat (construcao de Brasilia)",
    ),
    (
        "Cryptonanus ignitus",
        "Opossum-gracioso-de-barriga-vermelha",
        "Didelphimorphia",
        "Argentina",
        1962,
        "IUCN 2016",
        2016,
        "Americas",
        "Desmatamento, perda de habitat",
    ),
    (
        "Macrotis leucura",
        "Bilby-menor / Yallara",
        "Peramelemorphia",
        "Australia central",
        1967,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por gatos e raposas, alteracao de habitat",
    ),
    (
        "Pteropus tokudae",
        "Raposa-voadora-de-Guam",
        "Chiroptera",
        "Guam (Ilhas Marianas, Micronesia)",
        1968,
        "IUCN 2017",
        2017,
        "Oceano",
        "Caca (como alimento), perda de habitat",
    ),
    (
        "Gazella saudiya",
        "Gazela-da-arabia-saudita",
        "Artiodactyla",
        "Peninsula Arabica",
        1970,
        "IUCN 2008",
        2008,
        "Asia",
        "Caca intensiva, degradacao de habitat",
    ),
    (
        "Nyctophilus howensis",
        "Morcego-de-orelhas-longas-de-Lord-Howe",
        "Chiroptera",
        "Ilha Lord Howe, Australia",
        1972,
        "IUCN 2017",
        2017,
        "Oceano",
        "Desmatamento, especies invasoras",
    ),
    (
        "Zalophus japonicus",
        "Leao-marinho-japones",
        "Carnivora",
        "Japao, Coreia, Russia",
        1951,
        "IUCN 2008",
        2008,
        "Asia",
        "Caca comercial, captura incidental por pesca",
    ),
    (
        "Lutra nippon",
        "Lontra-do-Japao",
        "Carnivora",
        "Japao",
        1979,
        "lit. 2012",
        2012,
        "Asia",
        "Caca, poluicao hidrica, perda de habitat",
    ),
    (
        "Crocidura trichura",
        "Musaranho-de-Christmas",
        "Eulipotyphla",
        "Ilha Christmas",
        1985,
        "IUCN 2025",
        2025,
        "Oceano",
        "Especies invasoras (gatos, ratos, formigas loucas)",
    ),
    (
        "Isolobodon portoricensis",
        "Hutia-de-Porto-Rico",
        "Rodentia",
        "Hispaniola (introd. Porto Rico, USVI)",
        1900,
        "IUCN 2008",
        2008,
        "Caribe",
        "Caca, especies invasoras",
    ),
    (
        "Notomys robustus",
        "Grande rato-saltador",
        "Rodentia",
        "Australia (Flinders e Davenport)",
        1902,
        "IUCN 2016",
        2016,
        "Australia",
        "Predacao por especies invasoras, perda de habitat",
    ),
    (
        "Pipistrellus murrayi",
        "Pipistrelo-de-Christmas",
        "Chiroptera",
        "Ilha Christmas",
        2009,
        "IUCN 2017",
        2017,
        "Oceano",
        "Formigas-loucas amarelas, serpentes-lobo, perda de habitat",
    ),
    (
        "Melomys rubicola",
        "Melomis-de-Bramble-Cay",
        "Rodentia",
        "Bramble Cay, Australia",
        2009,
        "IUCN 2015",
        2015,
        "Oceano",
        "Elevacao do nivel do mar (mudanca climatica)",
    ),
    (
        "Uromys porculus",
        "Rato-de-Guadalcanal",
        "Rodentia",
        "Ilha de Guadalcanal (Ilhas Salomao)",
        1888,
        "IUCN 2016",
        2016,
        "Oceano",
        "Especies invasoras (gatos) e perda de habitat",
    ),
    (
        "Quemisia gravis",
        "Hutia-gigante-de-Hispaniola",
        "Rodentia",
        "Hispaniola (Haiti/Rep. Dom.)",
        1500,
        "IUCN 2016",
        2016,
        "Caribe",
        "Colonizacao europeia, caca, especies invasoras",
    ),
    (
        "Megalomys audreyae",
        "Rato-gigante-de-Barbuda",
        "Rodentia",
        "Barbuda",
        1500,
        "IUCN 2016",
        2016,
        "Caribe",
        "Colonizacao europeia, especies invasoras",
    ),
    (
        "Hippopotamus laloumena",
        "Hipopotamo-de-madagascar",
        "Artiodactyla",
        "Madagascar",
        1500,
        "lit. 2014",
        2014,
        "Madagascar",
        "Caca intensiva humana e perda de ecossistema",
    ),
    (
        "Mystacina robusta",
        "Morcego-de-cauda-curta-maior",
        "Chiroptera",
        "Nova Zelandia (Ilha Sul e Ilhas Stewart)",
        1967,
        "IUCN 2019",
        2019,
        "Oceano",
        "Predacao por ratos-negros introduzidos",
    ),
    (
        "Pteropus melanotus natalis",
        "Morcego-voador-de-Christmas",
        "Chiroptera",
        "Ilha Christmas, Australia",
        1986,
        "IUCN 2017",
        2017,
        "Oceano",
        "Formigas-loucas amarelas, gatos ferais, destruicao de habitat",
    ),
    (
        "Nesoryzomys narboroughi",
        "Rato-de-Fernandina das Galapagos",
        "Rodentia",
        "Ilha Fernandina, Galapagos",
        1906,
        "IUCN 2008",
        2008,
        "Oceano",
        "Especies invasoras introduzidas por navios; erupcao vulcanica 1906",
    ),
    (
        "Brotomys contractus",
        "Rato-comestivel-menor de Hispaniola",
        "Rodentia",
        "Hispaniola (Haiti/Rep. Dom.)",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, caca, especies invasoras",
    ),
    (
        "Heteropsomys antillensis",
        "Rato-de-caverna maior de Porto Rico",
        "Rodentia",
        "Porto Rico",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, especies invasoras (ratos)",
    ),
    (
        "Elasmodontomys obliquus",
        "Rato-de-dente-obliquo de Porto Rico",
        "Rodentia",
        "Porto Rico",
        1500,
        "IUCN 2008",
        2008,
        "Caribe",
        "Colonizacao europeia, especies invasoras",
    ),
    (
        "Nesophontes longirostris",
        "Nesofonte-de-focinho-longo-cubano",
        "Eulipotyphla",
        "Cuba",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao europeia, especies invasoras (ratos, mongooses)",
    ),
    (
        "Nesophontes superstes",
        "Nesofonte-hispanoiola-menor",
        "Eulipotyphla",
        "Hispaniola",
        1500,
        "IUCN 2017",
        2017,
        "Caribe",
        "Colonizacao europeia, especies invasoras",
    ),
    (
        "Megalomys cubanensis",
        "Rato-gigante-de-Cuba",
        "Rodentia",
        "Cuba",
        1500,
        "IUCN 2016",
        2016,
        "Caribe",
        "Colonizacao europeia, caca, especies invasoras",
    ),
    (
        "Oryzomys gorgasi",
        "Rato-de-arroz de Gorgas",
        "Rodentia",
        "Colombia e Panama",
        1900,
        "IUCN 2008",
        2008,
        "Americas",
        "Destruicao de habitat (manguezais), especies invasoras",
    ),
    (
        "Crocidura ultima",
        "Musaranho-de-Pohnpei",
        "Eulipotyphla",
        "Ilha de Pohnpei, Micronesia",
        1900,
        "IUCN 2017",
        2017,
        "Oceano",
        "Especies invasoras, perda de habitat",
    ),
]

print("=" * 70)
print("SINCRONIZACAO v18 - 114 ESPECIES VALIDADAS")
print("=" * 70)

species_index = {s[0]: s for s in SPECIES_DATA}
print(f"\nEspecies na lista: {len(SPECIES_DATA)}")

existing = {m.binomial_name: m for m in Mammal.objects.all()}
print(f"Especies no banco: {len(existing)}")

updated = 0
created = 0
deleted = 0
errors = []

for (
    binomial,
    common,
    order,
    location,
    ext_year,
    form_source,
    form_year,
    reg,
    cause,
) in SPECIES_DATA:
    try:
        if binomial in existing:
            m = existing[binomial]
            m.common_name = common
            m.taxonomy_order = order
            m.distribution = location
            m.extinction_year = ext_year
            m.formalization_year = form_year
            m.formalization_source = form_source
            m.region = reg
            m.main_cause = cause
            m.extinction_era = str(ext_year)
            m.save()
            updated += 1
        else:
            m = Mammal.objects.create(
                binomial_name=binomial,
                common_name=common,
                taxonomy_order=order,
                distribution=location,
                description=f"{common} ({binomial}) e uma especie extinta de mamifero da ordem {order}. Habitava {location}. Sua extincao biologica ocorreu por volta de {ext_year}, sendo formalmente reconhecida em {form_year} ({form_source}). Causa principal: {cause}.",
                extinction_year=ext_year,
                formalization_year=form_year,
                formalization_source=form_source,
                region=reg,
                main_cause=cause,
                extinction_era=str(ext_year),
                extinction_causes=cause,
            )
            created += 1
            print(f"  CRIADO: {common} ({binomial})")
    except Exception as e:
        errors.append(f"{binomial}: {e}")
        print(f"  ERRO: {binomial} - {e}")

for binomial, mammal in existing.items():
    if binomial not in species_index:
        print(f"  DELETADO: {mammal.common_name} ({binomial})")
        mammal.delete()
        deleted += 1

print("\n" + "=" * 70)
print("RELATORIO FINAL")
print("=" * 70)
print(f"  Atualizadas: {updated}")
print(f"  Criadas:     {created}")
print(f"  Deletadas:   {deleted}")
print(f"  Erros:       {len(errors)}")
print(f"  Total final: {Mammal.objects.count()}")
if errors:
    print("\nERROS:")
    for e in errors:
        print(f"  - {e}")
print("=" * 70)
