# Generated by Django 5.2.7 on 2025-10-13 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mammal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(help_text='Nome popular do mamífero', max_length=200, verbose_name='Nome Comum')),
                ('binomial_name', models.CharField(help_text='Nome binomial (científico) do mamífero', max_length=200, verbose_name='Nome Científico')),
                ('description', models.TextField(help_text='Descrição detalhada do mamífero', verbose_name='Descrição')),
                ('habitat', models.TextField(blank=True, help_text='Habitat natural do mamífero', null=True, verbose_name='Habitat')),
                ('distribution', models.TextField(blank=True, help_text='Distribuição geográfica', null=True, verbose_name='Distribução')),
                ('extinction_causes', models.TextField(blank=True, help_text='Principais causas que levaram à extinção', null=True, verbose_name='Causas da Extinção')),
                ('image_filename', models.CharField(blank=True, help_text='Nome do arquivo de imagem na pasta static/images', max_length=255, null=True, verbose_name='Nome do Arquivo de Imagem')),
                ('continent', models.CharField(blank=True, help_text='Continente onde o mamífero habitava', max_length=100, null=True, verbose_name='Continente')),
                ('taxonomy_order', models.CharField(blank=True, help_text='Ordem taxonômica do mamífero', max_length=100, null=True, verbose_name='Ordem Taxonômica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Mamífero Extinto',
                'verbose_name_plural': 'Mamíferos Extintos',
                'ordering': ['common_name'],
                'indexes': [models.Index(fields=['common_name'], name='mammals_mam_common__006db6_idx'), models.Index(fields=['continent'], name='mammals_mam_contine_7cb82a_idx'), models.Index(fields=['taxonomy_order'], name='mammals_mam_taxonom_1616a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Favoritado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('mammal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='mammals.mammal', verbose_name='Mamífero')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='mammals_fav_user_id_c4967d_idx'), models.Index(fields=['mammal'], name='mammals_fav_mammal__a4d5ba_idx')],
                'unique_together': {('user', 'mammal')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Conteúdo do comentário', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('mammal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mammals.mammal', verbose_name='Mamífero')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mammal', '-created_at'], name='mammals_com_mammal__00650b_idx'), models.Index(fields=['user'], name='mammals_com_user_id_f28a89_idx')],
            },
        ),
    ]
