# Generated by Django 5.0.14 on 2026-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0002_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rating',
            new_name='mammals_rat_user_id_56fb2e_idx',
            old_name='mammals_rat_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='mammals_rat_mammal__78cebb_idx',
            old_name='mammals_rat_mammal_id_idx',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='mammals_rat_score_ab2000_idx',
            old_name='mammals_rat_score_idx',
        ),
        migrations.AddField(
            model_name='mammal',
            name='diet',
            field=models.CharField(blank=True, help_text='O que este animal comia? (ex: Herbívoro, Carnívoro...)', max_length=255, null=True, verbose_name='Dieta'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='extinction_era',
            field=models.CharField(blank=True, help_text='Quando foi visto pela última vez? (ex: Anos 1930, Século XVII)', max_length=255, null=True, verbose_name='Época da Extinção'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='fun_facts',
            field=models.TextField(blank=True, help_text='Fatos ou observações interessantes adicionais', null=True, verbose_name='Curiosidades'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='image',
            field=models.ImageField(blank=True, help_text='Faça upload de uma foto para o mamífero', null=True, upload_to='mammals/', verbose_name='Foto/Imagem Oficial'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='size_weight',
            field=models.CharField(blank=True, help_text='Ex: 1,5m de altura, 200kg', max_length=255, null=True, verbose_name='Tamanho e Peso'),
        ),
        migrations.AlterField(
            model_name='mammal',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Nome do arquivo de imagem na pasta static/images (Legado)', max_length=255, null=True, verbose_name='Nome Herança Antigo'),
        ),
    ]
