# Generated by Django 5.0.14 on 2026-03-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mammals",
            "0003_rename_mammals_rat_user_id_idx_mammals_rat_user_id_56fb2e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mammal",
            name="conservation_legacy",
            field=models.TextField(
                blank=True,
                help_text="Museus, registros históricos, esforços de conservação e importância cultural",
                null=True,
                verbose_name="Conservação e Legado",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="ecological_impact",
            field=models.TextField(
                blank=True,
                help_text="Papel deste animal no ecossistema e impacto de sua extinção",
                null=True,
                verbose_name="Impacto Ecológico",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Coordenada de latitude para posição no mapa",
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Coordenada de longitude para posição no mapa",
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="taxonomy_extended",
            field=models.TextField(
                blank=True,
                help_text="Família, Gênero e outras informações taxonômicas adicionais",
                null=True,
                verbose_name="Taxonomia Estendida",
            ),
        ),
    ]
