# Generated by Django 5.0.14 on 2026-06-18 05:17

from django.db import migrations, models

import mammals.models


class Migration(migrations.Migration):

    dependencies = [
        ("mammals", "0005_mammal_scientific_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="mammal",
            name="extinction_year",
            field=models.IntegerField(
                blank=True,
                help_text="Último registro vivo confirmado (ano)",
                null=True,
                verbose_name="Ano de Extinção Biológica",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="formalization_source",
            field=models.CharField(
                blank=True,
                help_text="Ex: IUCN 2008, lit. 1903",
                max_length=100,
                null=True,
                verbose_name="Fonte da Formalização",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="formalization_year",
            field=models.IntegerField(
                blank=True,
                help_text="Ano da declaração formal de extinção (IUCN ou literatura)",
                null=True,
                verbose_name="Ano de Formalização",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="main_cause",
            field=models.TextField(
                blank=True,
                help_text="Causa principal da extinção",
                null=True,
                verbose_name="Causa Principal",
            ),
        ),
        migrations.AddField(
            model_name="mammal",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Região geográfica (Americas, Caribe, Australia, etc.)",
                max_length=100,
                null=True,
                verbose_name="Região",
            ),
        ),
        migrations.AlterField(
            model_name="mammal",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Faça upload de uma foto para o mamífero",
                null=True,
                upload_to=mammals.models.safe_mammal_image_path,
                validators=[mammals.models.validate_image_extension],
                verbose_name="Foto/Imagem Oficial",
            ),
        ),
    ]
