# Generated by Django 5.0.14 on 2026-06-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0006_mammal_extinction_year_mammal_formalization_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
