# Generated by Django 5.0.14 on 2026-06-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0008_alter_comment_user_alter_favorite_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mammal',
            index=models.Index(fields=['extinction_year'], name='mammals_mam_extinct_93f083_idx'),
        ),
        migrations.AddIndex(
            model_name='mammal',
            index=models.Index(fields=['formalization_year'], name='mammals_mam_formali_def651_idx'),
        ),
        migrations.AddIndex(
            model_name='mammal',
            index=models.Index(fields=['-updated_at'], name='mammals_mam_updated_93e27e_idx'),
        ),
    ]
