# Generated by Django 5.0.14 on 2026-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0009_mammal_mammals_mam_extinct_93f083_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammal',
            name='diet',
            field=models.TextField(blank=True, help_text='O que este animal comia? (ex: Herbívoro, Carnívoro...)', null=True, verbose_name='Dieta'),
        ),
        migrations.AlterField(
            model_name='mammal',
            name='extinction_era',
            field=models.TextField(blank=True, help_text='Quando foi visto pela última vez? (ex: Anos 1930, Século XVII)', null=True, verbose_name='Época da Extinção'),
        ),
        migrations.AlterField(
            model_name='mammal',
            name='size_weight',
            field=models.TextField(blank=True, help_text='Ex: 1,5m de altura, 200kg', null=True, verbose_name='Tamanho e Peso'),
        ),
    ]
