# Generated by Django 5.0.14 on 2026-08-28 01:35

import os
from django.db import migrations
from django.core.management import call_command
from django.conf import settings

def load_initial_data(apps, schema_editor):
    fixture_path = os.path.join(settings.BASE_DIR, 'initial_mammals_v2.json')
    if os.path.exists(fixture_path):
        try:
            call_command('loaddata', fixture_path)
            print("Loaded initial_mammals_v2.json successfully")
        except Exception as e:
            print(f"Error loading fixture: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0010_alter_mammal_diet_alter_mammal_extinction_era_and_more'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
